- name: ipconfig save as local file
  hosts: all 
   
  tasks:
    - name: run ipconfig save result to local file
      win_package: 
        path: 'C:\windows\system32\ipconfig.exe'
        product_id: 000888
        arguments: '/all > c:\test\result1.txt'
