- name: Install all security updates with automatic reboots
  hosts: all 
 
  tasks:
  - name: Install all security updates with automatic reboots
    win_updates:
      category_names:
      - SecurityUpdates
      reboot: yes
