- name: Uninstall DI agent and delete the temp file
  hosts: all 
  
  tasks:
  
     - name: Uninstall diagent
       win_package:
        path: 'C:\Temp\deployment\DeepInstinct\2.3.2.5_InstallerManaged_deep.exe'
        product_Id: 8F276E88-8C75-44AA-A245-7112AE5AF2DA
        arguments: '/x DIUIpass12!'
        
    - name: Delete directory structure
      win_file:
        path: C:\Temp\deployment\DeepInstinct
        state: absent
        
    - name: Unconditionally reboot the machine with all defaults
      reboot:
