- name: Uninstall DI agent and delete the temp file
  hosts: all 
  
  tasks:
  
        
    - name: Run regedit.exe locally (on target node) as SYSTEM and interactively
      win_psexec:
        command: 'C:\Temp\deployment\DeepInstinct\2.3.2.5_InstallerManaged_deep.exe /x DIUIpass12!'
        system: yes
        
    - name: Delete directory structure
      win_file:
        path: C:\Temp\deployment\DeepInstinct
        state: absent
        
    - name: Unconditionally reboot the machine with all defaults
      reboot:
